[package]
name = "kv_common"
version = "0.1.0"
edition = "2021"

[dependencies]
tarpc.workspace = true
thiserror.workspace = true
serde.workspace = true
env_logger.workspace = true
log.workspace = true
futures.workspace = true

