name: build-by-branch

on:
  push:
    branches:
    - main
    - feature/*
    - fix/*
    paths-ignore:
    - "**.md"
  pull_request:
   branches:
   - main
   paths-ignore:
   - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: LAB1 Check code style
      run: cargo fmt -- --check
      working-directory: ./lab1
    - name: LAB1 Build
      run: cargo build --release --all-features
      working-directory: ./lab1
    - name: LAB1 Check code
      run: cargo clippy
      working-directory: ./lab1
    - name: LAB1 Tests
      run: cargo test --test test_runner --release
      working-directory: ./lab1

    - name: LAB2 Check code style
      run: cargo fmt -- --check
      working-directory: ./lab2
    - name: LAB2 Build
      run: cargo build --release --all-features
      working-directory: ./lab2
    - name: LAB2 Check code
      run: cargo clippy
      working-directory: ./lab2
    - name: LAB2 Unit Tests
      run: cargo test --release
      working-directory: ./lab2
    - name: LAB2 Integration Tests
      run: cargo test --release
      working-directory: ./lab2
